---
ansible_host: host-ip2
ansible_user: changeme
#ansible_become_password: "{{ vault_ansible_become_password }}"
verify: false
# The path to the root of IBM python installation
PYZ: "/usr/lpp/IBM/cyp/v3r10/pyz"

# The path to root of ZOAU installation
ZOAU: "/usr/lpp/IBM/zoautil"

ansible_python_interpreter: "{{ PYZ }}/bin/python3"

# You should not need to change environment_vars
environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  PYTHONPATH: "{{ ZOAU }}/lib"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
  PYTHONSTDINENCODING: "cp1047"


